sudo: false
language: node_js
node_js:
- 4.1

script:
  - npm test && npm run test-travis

after_failure:
  - for file in *.log; do echo $file; echo "======================"; cat $file; done || true

